
strategy:
  matrix:
    linux:
      imageName: 'ubuntu-18.04'
    mac:
      imageName: 'macos-10.15'
    windows:
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)

trigger:
- master

steps:

- script: git submodule init && git submodule update
  displayName: 'Load git submodules'

- script: python build_and_test.py rebuild
  displayName: "Build and Test"
