
trigger:
- master

name: "0.3.0"

jobs:

- job: "Build"
  strategy:
    matrix:
      Linux:
        imageName: 'ubuntu-latest'
      # mac:
      #   imageName: 'macos-latest'
      Windows:
        imageName: 'windows-latest'

  pool:
    vmImage: $(imageName)

  steps:
  - script: git submodule init && git submodule update
    displayName: 'Load git submodules'

  - script: python build_and_test.py rebuild
    displayName: "Build and Test"
