
strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

trigger:
- master

steps:
# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '3.7'
#     architecture: 'x64'

# - script: python -m pip install -r requirements.txt
#   displayName: 'Install dependencies'
#

- script: msbuild win/irig106.sln
  displayName: 'Build (Windows)'
  condition: eq( variables['Agent.OS'], 'Windows_NT' )

- script: make
  displayName: 'Build (Unix)'
  condition: neq( variables['Agent.OS'], 'Linux' )

- script: git submodule init && git submodule update
  displayName: 'Load git submodules'

- script: make test
  displayName: 'Run tests'

# - task: PublishTestResults@2
#   inputs:
#     testResultsFormat: 'JUnit'
#     testResultsFiles: '**/test-results.xml'
#     testRunTitle: 'Python $(python.version)'
#   condition: succeededOrFailed()

# - task: PublishPipelineArtifact@0
#   displayName: 'Publish binary'
#   inputs:
#     artifactName: 'witdb'
#     targetPath: 'dist/witdb.exe'

# - script: python -m pip download -r requirements.txt -d ./deps
#   displayName: 'Download dependencies'

# - task: ArchiveFiles@2
#   displayName: 'Zip dependencies'
#   inputs:
#     rootFolderOrFile: 'deps' 
#     includeRootFolder: true 
#     archiveType: 'zip'
#     archiveFile: 'deps.zip' 
#     replaceExistingArchive: true 

# - task: PublishPipelineArtifact@0
#   displayName: 'Publish dependencies'
#   inputs:
#     artifactName: 'dependencies'
#     targetPath: 'deps.zip'
